{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "anythingllm.selectorLabels" . | nindent 6 }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
