{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "anythingllm.fullname" . }}
  labels:
    {{- include "anythingllm.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "anythingllm.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace }}
  endpoints:
    - port: {{ .Values.metrics.portName }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  {{- with .Values.metrics.serviceMonitor.additionalEndpoints }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
